version: '3.2'
services:

  icap-dhis-web:
    build:
        context: ./apache
    container_name: icap-dhis-web
    ports:
        - "80:80"
        - "443:443"
    networks: 
        - network
    volumes:
        - type: bind
          source: /opt/dhis/data
          target: /usr/local/apache2/htdocs
        - type: bind
          source: /etc/letsencrypt/live
          target: /etc/letsencrypt/live
    depends_on:
        - "icap-dhis-tomcat"
    restart: unless-stopped

  icap-dhis-tomcat:
    build:
      context: ./tomcat
    container_name: icap-dhis-tomcat
    ports:
      - "8080:8080"
    networks: 
      - network
    depends_on:   
      - "icap-dhis-db"
    volumes: 
      - type: bind
        source: /opt/dhis/data/war
        target: /usr/local/tomcat/webapps 
    restart: unless-stopped
   
  icap-dhis-db:
    build: ./database
    ports: 
       - "5432:5432"
    container_name: icap-dhis-db
    networks: 
      - network
    volumes:
      - type: volume
        source: dbdata
        target: /opt/dhis/data
    restart: unless-stopped

networks: 
  network:
    driver: bridge

volumes:
  dbdata:
